export const DATA_PROVIDER_END_POINT_LIST = {
  VOTING_CENTER: 'user-voting-centers',
  POLLING_CENTER: 'polling-centers',
  ELECTION_SETTING: 'election-settings',
  VOTE_COUNT: 'settings-wise-vote-count',
  PRESIDING_OFFICER: 'presiding-officers',
  POLLING_CENTER_RESULT: 'polling-center-result',
  CANDIDATES: 'candidates',
  ELECTION: '',
  CANDIDATE_VOTE_COUNT: 'candidate-vote-count',
  UNCONTESTED_CANDIDATE_VOTE_COUNT: 'uncontested-candidate-vote-count',
  DIVISION_WISE_VOTER_COUNT: 'division-wise-voter-count',
  SETTING_WISE_VOTER_COUNT: 'settings-wise-voter-count',
};

export const DATA_PROVIDER_HISTORY_LIST = {
  VOTING_CENTER: 'USER_VOTING_CENTERS',
  POLLING_CENTER: 'POLLING_CENTERS',
  ELECTION_SETTING: 'ELECTION_SETTINGS',
  VOTE_COUNT: 'SETTINGS_WISE_VOTE_COUNT',
  PRESIDING_OFFICER: 'PRESIDING_OFFICER',
  POLLING_CENTER_RESULT: 'POLLING_CENTER_RESULT',
  CANDIDATES: 'CANDIDATE',
  ELECTION: 'ELECTION_SCHEDULE',
  CANDIDATE_VOTE_COUNT: 'CANDIDATE_VOTE_COUNT',
  UNCONTESTED_CANDIDATE_VOTE_COUNT: 'UNCONTESTED_CANDIDATE_VOTE_COUNT',
  DIVISION_WISE_VOTER_COUNT: 'DIVISION_WISE_VOTER_COUNT',
  SETTING_WISE_VOTER_COUNT: 'SETTINGS_WISE_VOTER_COUNT',
  ALL: 'ALL',
};

export const RUNNING_STATUS="RUNNING"
