export const GET_COLLATERAL_FORM_INFO = {
  GET_COLLATERAL_FORM_INFO_REQUEST: 'GET_COLLATERAL_FORM_INFO_REQUEST',
  GET_COLLATERAL_FORM_INFO_SUCCESS: 'GET_COLLATERAL_FORM_INFO_SUCCESS',
  GET_COLLATERAL_FORM_INFO_FAILED: 'GET_COLLATERAL_FORM_INFO_FAILED',
};

export const UPDATE_COLLATERAL_FORM_INFO = {
  UPDATE_COLLATERAL_FORM_INFO_REQUEST: 'UPDATE_COLLATERAL_FORM_INFO_REQUEST',
  UPDATE_COLLATERAL_FORM_INFO_SUCCESS: 'UPDATE_COLLATERAL_FORM_INFO_SUCCESS',
  UPDATE_COLLATERAL_FORM_INFO_FAILED: 'UPDATE_COLLATERAL_FORM_INFO_FAILED',
  UPDATE_COLLATERAL_FORM_INFO_RESET: 'UPDATE_COLLATERAL_FORM_INFO_RESET',
};
