export const CREATE_AFFIDAVIT_STEP_ONE = {
  CREATE_AFFIDAVIT_STEP_ONE_REQUEST: 'CREATE_AFFIDAVIT_STEP_ONE_REQUEST',
  CREATE_AFFIDAVIT_STEP_ONE_SUCCESS: 'CREATE_AFFIDAVIT_STEP_ONE_SUCCESS',
  CREATE_AFFIDAVIT_STEP_ONE_FAILED: 'CREATE_AFFIDAVIT_STEP_ONE_FAILED',
  CREATE_AFFIDAVIT_STEP_ONE_INITIAL_STATE:
    'CREATE_AFFIDAVIT_STEP_ONE_INITIAL_STATE',
};

export const UPDATE_AFFIDAVIT_STEP_ONE = {
  UPDATE_AFFIDAVIT_STEP_ONE_REQUEST: 'UPDATE_AFFIDAVIT_STEP_ONE_REQUEST',
  UPDATE_AFFIDAVIT_STEP_ONE_SUCCESS: 'UPDATE_AFFIDAVIT_STEP_ONE_SUCCESS',
  UPDATE_AFFIDAVIT_STEP_ONE_FAILED: 'UPDATE_AFFIDAVIT_STEP_ONE_FAILED',
};

export const GET_AFFIDAVIT_STEP_ONE = {
  GET_AFFIDAVIT_STEP_ONE_REQUEST: 'GET_AFFIDAVIT_STEP_ONE_REQUEST',
  GET_AFFIDAVIT_STEP_ONE_SUCCESS: 'GET_AFFIDAVIT_STEP_ONE_SUCCESS',
  GET_AFFIDAVIT_STEP_ONE_FAILED: 'GET_AFFIDAVIT_STEP_ONE_FAILED',
};

export const GET_ALL_PRESENT_CASE = {
  GET_ALL_PRESENT_CASE_REQUEST: 'GET_ALL_PRESENT_CASE_REQUEST',
  GET_ALL_PRESENT_CASE_SUCCESS: 'GET_ALL_PRESENT_CASE_SUCCESS',
  GET_ALL_PRESENT_CASE_FAILED: 'GET_ALL_PRESENT_CASE_FAILED',
};

export const GET_PRESENT_CASE = {
  GET_PRESENT_CASE_REQUEST: 'GET_PRESENT_CASE_REQUEST',
  GET_PRESENT_CASE_SUCCESS: 'GET_PRESENT_CASE_SUCCESS',
  GET_PRESENT_CASE_FAILED: 'GET_PRESENT_CASE_FAILED',
};

export const UPDATE_PRESENT_CASE = {
  UPDATE_PRESENT_CASE_REQUEST: 'UPDATE_PRESENT_CASE_REQUEST',
  UPDATE_PRESENT_CASE_SUCCESS: 'UPDATE_PRESENT_CASE_SUCCESS',
  UPDATE_PRESENT_CASE_FAILED: 'UPDATE_PRESENT_CASE_FAILED',
};

export const DELETE_PRESENT_CASE = {
  DELETE_PRESENT_CASE_REQUEST: 'DELETE_PRESENT_CASE_REQUEST',
  DELETE_PRESENT_CASE_SUCCESS: 'DELETE_PRESENT_CASE_SUCCESS',
  DELETE_PRESENT_CASE_FAILED: 'DELETE_PRESENT_CASE_FAILED',
};
