export const CREATE_ASSET_LIABILITY_DETAILS = {
  CREATE_ASSET_LIABILITY_DETAILS_REQUEST:
    'CREATE_ASSET_LIABILITY_DETAILS_REQUEST',
  CREATE_ASSET_LIABILITY_DETAILS_SUCCESS:
    'CREATE_ASSET_LIABILITY_DETAILS_SUCCESS',
  CREATE_ASSET_LIABILITY_DETAILS_FAILED:
    'CREATE_ASSET_LIABILITY_DETAILS_FAILED',
  CREATE_ASSET_LIABILITY_DETAILS_INITIAL_STATE:
    'CREATE_ASSET_LIABILITY_DETAILS__INITIAL_STATE',
};

export const GET_ASSET_LIABILITY_DETAILS = {
  GET_ASSET_LIABILITY_DETAILS_REQUEST: 'GET_ASSET_LIABILITY_DETAILS_REQUEST',
  GET_ASSET_LIABILITY_DETAILS_SUCCESS: 'GET_ASSET_LIABILITY_DETAILS_SUCCESS',
  GET_ASSET_LIABILITY_DETAILS_FAILED: 'GET_ASSET_LIABILITY_DETAILS_FAILED',
};

export const UPDATE_ASSET = {
  UPDATE_ASSET_REQUEST: 'UPDATE_ASSET_REQUEST',
  UPDATE_ASSET_SUCCESS: 'UPDATE_ASSET_SUCCESS',
  UPDATE_ASSET_FAILED: 'UPDATE_ASSET_FAILED',
};

export const UPDATE_YEARLY_INCOME = {
  UPDATE_YEARLY_INCOME_REQUEST: 'UPDATE_YEARLY_INCOME_REQUEST',
  UPDATE_YEARLY_INCOME_SUCCESS: 'UPDATE_YEARLY_INCOME_SUCCESS',
  UPDATE_YEARLY_INCOME_FAILED: 'UPDATE_YEARLY_INCOME_FAILED',
};

export const DELETE_ASSET = {
  DELETE_ASSET_REQUEST: 'DELETE_ASSET_REQUEST',
  DELETE_ASSET_SUCCESS: 'DELETE_ASSET_SUCCESS',
  DELETE_ASSET_FAILED: 'DELETE_ASSET_FAILED',
};

export const DELETE_YEARLY_INCOME = {
  DELETE_YEARLY_INCOME_REQUEST: 'DELETE_YEARLY_INCOME_REQUEST',
  DELETE_YEARLY_INCOME_SUCCESS: 'DELETE_YEARLY_INCOME_SUCCESS',
  DELETE_YEARLY_INCOME_FAILED: 'DELETE_YEARLY_INCOME_FAILED',
};
