import { CANDIDATE_INFO_MANAGEMENT } from '@constants/forms/candidate-info-management/candidate-info-management';

export const POSTER_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.POSTER_EXPENSE;

export const ELECTION_OFFICE_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .ELECTION_OFFICE_EXPENSE;

export const CANDIDATE_CENTRAL_OFFICE_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .CANDIDATE_CENTRAL_OFFICE_EXPENSE;

export const CANDIDATE_TRAVEL_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .CANDIDATE_TRAVEL_EXPENSE;

export const DOMESTIC_MEETING_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .DOMESTIC_MEETING_EXPENSE;

export const LEAFLET_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.LEAFLET_EXPENSE;

export const HANDBILL_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.HANDBILL_EXPENSE;

export const BANNER_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.BANNER_EXPENSE;

export const DIGITAL_BANNER_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .DIGITAL_BANNER_EXPENSE;

export const ROAD_MEETING_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.ROAD_MEETING_EXPENSE;

export const MIKING_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.MIKING_EXPENSE;

export const PORTRAIT_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.PORTRAIT_EXPENSE;

export const SYMBOL_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.SYMBOL_EXPENSE;

export const OFFICE_INVITATION_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .OFFICE_INVITATION_EXPENSE;

export const STAFF_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.STAFF_EXPENSE;

export const ADVERTISEMENT_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS
    .ADVERTISEMENT_EXPENSE;

export const OTHER_EXPENSE =
  CANDIDATE_INFO_MANAGEMENT.OPERATOR.INCOME_SOURCE_DETAILS.OTHER_EXPENSE;
