export const CREATE_FOURTH_PART = {
  CREATE_FOURTH_PART_REQUEST: 'CREATE_CANDIDATE_NOMINATION_FORM_FOURTH_REQUEST',
  CREATE_FOURTH_PART_SUCCESS: 'CREATE_CANDIDATE_NOMINATION_FORM_FOURTH_SUCCESS',
  CREATE_FOURTH_PART_FAILED: 'CREATE_CANDIDATE_NOMINATION_FORM_FOURTH_FAILED',
  CREATE_FOURTH_PART_INITIAL_STATE: 'CREATE_FOURTH_PART_INITIAL_STATE',
};

export const GET_FOURTH_PART = {
  GET_FOURTH_PART_REQUEST: 'GET_CANDIDATE_NOMINATION_FORM_FOURTH_PART_REQUEST',
  GET_FOURTH_PART_SUCCESS: 'GET_CANDIDATE_NOMINATION_FORM_FOURTH_PART_SUCCESS',
  GET_FOURTH_PART_FAILED: 'GET_CANDIDATE_NOMINATION_FORM_FOURTH_PART_FAILED',
  GET_FOURTH_PART_INITIAL_STATE: 'GET_FOURTH_PART_INITIAL_STATE',
};
