export const CREATE_FIRST_PART = {
  CREATE_FIRST_PART_REQUEST:
    'CREATE_CANDIDATE_NOMINATION_FORM_FIRST_PART_REQUEST',
  CREATE_FIRST_PART_SUCCESS:
    'CREATE_CANDIDATE_NOMINATION_FORM_FIRST_PART_SUCCESS',
  CREATE_FIRST_PART_FAILED:
    'CREATE_CANDIDATE_NOMINATION_FORM_FIRST_PART_FAILED',
  CREATE_FIRST_PART_INITIAL_STATE:
    'CREATE_CANDIDATE_NOMINATION_FORM_FIRST_PART_INITIAL_STATE',
};

export const GET_FIRST_PART = {
  GET_FIRST_PART_REQUEST: 'GET_CANDIDATE_NOMINATION_FORM_FIRST_PART_REQUEST',
  GET_FIRST_PART_SUCCESS: 'GET_CANDIDATE_NOMINATION_FORM_FIRST_PART_SUCCESS',
  GET_FIRST_PART_FAILED: 'GET_CANDIDATE_NOMINATION_FORM_FIRST_PART_FAILED',
  GET_FIRST_PART_INITIAL_STATE:
    'GET_CANDIDATE_NOMINATION_FORM_FIRST_PART_INITIAL_STATE',
};
