export const CREATE_THIRD_PART = {
  CREATE_THIRD_PART_REQUEST:
    'CREATE_CANDIDATE_NOMINATION_FORM_THIRD_PART_REQUEST',
  CREATE_THIRD_PART_SUCCESS:
    'CREATE_CANDIDATE_NOMINATION_FORM_THIRD_PART_SUCCESS',
  CREATE_THIRD_PART_FAILED:
    'CREATE_CANDIDATE_NOMINATION_FORM_THIRD_PART_FAILED',
  CREATE_THIRD_PART_INITIAL_STATE: 'CREATE_THIRD_PART_INITIAL_STATE',
};

export const GET_THIRD_PART = {
  GET_THIRD_PART_REQUEST: 'GET_CANDIDATE_NOMINATION_FORM_THIRD_PART_REQUEST',
  GET_THIRD_PART_SUCCESS: 'GET_CANDIDATE_NOMINATION_FORM_THIRD_PART_SUCCESS',
  GET_THIRD_PART_FAILED: 'GET_CANDIDATE_NOMINATION_FORM_THIRD_PART_FAILED',
  GET_THIRD_PART_INITIAL_STATE: 'GET_THIRD_PART_INITIAL_STATE',
};
