export const CANDIDATE_INFO = {
  NATIONAL_MEMBER_OF_PARLIAMENT: {
    ID: 1,
    NAME: 'MEMBER_OF_PARLIAMENT',
  },

  UPAZILLA_CHAIRMAN: {
    ID: 2,
    NAME: 'CHAIRMAN',
  },

  UPAZILLA_VICE_CHAIRMAN: {
    ID: 3,
    NAME: 'VICE_CHAIRMAN',
  },

  UPAZILLA_WOMEN_VICE_CHAIRMAN: {
    ID: 4,
    NAME: 'WOMEN_VICE_CHAIRMAN',
  },

  CITY_CORPORATION_MAYOR: {
    ID: 5,
    NAME: 'MAYOR',
  },

  CITY_CORPORATION_COUNCILLOR: {
    ID: 6,
    NAME: 'COUNSILOR',
  },

  CITY_CORPORATION_WOMAN_COUNCILLOR: {
    ID: 7,
    NAME: 'WOMAN_COUNSILOR',
  },

  UNION_PARISHAD_CHAIRMAN: {
    ID: 8,
    NAME: 'CHAIRMAN',
  },

  UNION_PARISHAD_GENERAL_MEMBER: {
    ID: 9,
    NAME: 'GENERAL_MEMBER',
  },

  UNION_PARISHAD_RESERVED_MEMBER: {
    ID: 10,
    NAME: 'RESERVED_MEMBER',
  },

  MUNICIPALITY_MAYOR: {
    ID: 11,
    NAME: 'MAYOR',
  },

  MUNICIPALITY_COUNCILLOR: {
    ID: 12,
    NAME: 'COUNSILOR',
  },

  MUNICIPALITY_RESERVED_COUNCILLOR: {
    ID: 13,
    NAME: 'WOMAN_COUNSILOR',
  },

  NATIONAL_RESERVED_WOMAN_MEMBER_OF_PARLIAMENT: {
    ID: 14,
    NAME: 'RESERVED_WOMAN_MEMBER_OF_PARLIAMENT',
  },

  ZILLA_PARISHAD_CHAIRMAN: {
    ID: 15,
    NAME: 'CHAIRMAN',
  },

  ZILLA_PARISHAD_GENERAL_WARD_COUNCILLOR: {
    ID: 16,
    NAME: 'GENERAL_WARD_COUNCILLOR',
  },

  ZILLA_PARISHAD_RESERVED_WARD_COUNCILLOR: {
    ID: 17,
    NAME: 'RESERVED_WARD_COUNCILLOR',
  },
};
