export const FILE_CATEGORY = {
  DEFAULT: 'DEFAULT',
  SYMBOLS: 'SYMBOLS',
  CANDIDATES: 'CANDIDATES',
  CIMS: 'CIMS',
  RMS: 'RMS',
  POLLING_CENTERS: 'POLLING_CENTERS',
  POLLING_PERSONNEL: 'POLLING_PERSONNEL',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  SCHEDULES: 'SCHEDULES',
};
