import { FORM_FIELDS } from './forms';

export const SEARCH_FIELD_REQUIRED = {
  ELECTION_TYPE: 'electionTypeId',
  ELECTION_SCHEDULE: 'electionScheduleId',
  CANDIDATE_TYPE: 'candidateTypeId',
  CONSTITUENCY_ID: 'constituencyId',
  ELECTION_SCHEDULE_USER: FORM_FIELDS.APPLICATION_SEARCH.USER,
  USER_ID: 'userId',
  REGION_ID: 'regionId',
  ZILLA_ID: 'zillaId',
  UPAZILA_ID: 'upazilaId',
  VOTE_CENTER_UPAZILA_ID: 'addCenterUpazilla',
  VOTE_CENTER_ELECTION_SETTINGS: 'addCenterElectionSettings',
  AGENCY_ID: 'agencyId',
  USER_TYPE: 'userTypeCode',
  POLLING_CENTER_ID: 'pollingCenterId',
  STATUS: 'status',
  RESULT_TYPE: 'resultType',
  UNION_OR_WARDS: 'unionOrWardIds',
  UNION_OR_WARD: 'unionOrWardId',
  ELECTION_SETTINGS_ID: 'electionSettingsId',
  ELECTION_SETTINGS_IDS: 'electionSettingsIds',
  MUNICIPALITY: 'municipalityId',
  DATE_FROM: 'fromDate',
  DATE_TO: 'toDate',
};
