export enum STEPS {
  CANDIDATE_CONFIRMATION = 1,
  VERIFY = 2,
  PICK_UP = 3,
  APPEAL = 4,
  WITHDRAWAL_OF_CANDIDATURE = 5,
  ELECTED_UNOPPOSED = 6,
  SYMBOL_ALLOCATION = 7,
  ONLINE_NOMINATED_CANDIDATE_ACKNOWLEDGMENT = 8,
  ONLINE_ACCEPT_CANCEL = 9,
}

export enum STEPS_TYPE {
  AVAILABLE_STATUSES = 'availableStatuses',
  FILTER_STATUSES = 'filterStatuses',
}

export const AVAILABLE_STATUSES = 'availableStatuses';
export const FILTER_STATUSES = 'filterStatuses';

export const AVAILABLE_STATUS_CODE = {
  ONLINE_NOMINATED_CANDIDATE: 2,
  APPEAL: '6,10,13',
  SYMBOL_ALLOCATION: '11,9',
  CANDIDATE_CONFIRMATION: '3,5',
  WITHDRAWAL_OF_CANDIDATURE: '11,9',
  PICK_UP: 14,
  VERIFY: 18,
  NOMINATION_DASHBOARD: '2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18',
};
