export const USER_TYPES = {
  RETURNING_OFFICER: 'RO',
  ASSISTANT_RETURNING_OFFICER: 'ARO',
  ADMIN: 'ADMIN',
  OPERATOR: 'OP',
  PRESIDING_OFFICER: 'PO',
  CANDIDATE: 'CANDIDATE',
  ARO_OP: 'ARO_OP',
  UPAZILA_ELECTION_OFFICER: 'UPAZILA_ELECTION_OFFICER',
};
