export const SIGN_IN = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',
  SIGN_IN_RESTORE: 'SIGN_IN_RESTORE',
};

export const SIGN_OUT = {
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
  SIGN_OUT_RESTORE: 'SIGN_OUT_RESTORE',
};

export const RESET_PASSWORD = {
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
  RESET_PASSWORD_RESTORE: 'RESET_PASSWORD_RESTORE',
};

export const UPDATE_PASSWORD = {
  UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILED: 'UPDATE_PASSWORD_FAILED',
  UPDATE_PASSWORD_RESTORE: 'UPDATE_PASSWORD_RESTORE',
};

export const USER_INFO = {
  USER_INFO_REQUEST: 'USER_INFO_REQUEST',
  USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
  USER_INFO_FAILED: 'USER_INFO_FAILED',
  USER_INFO_RESTORE: 'USER_INFO_RESTORE',
};
