export const CREATE_ATTACH_FILE = {
  CREATE_ATTACH_FILE_REQUEST: 'CREATE_ATTACH_FILE_REQUEST',
  CREATE_ATTACH_FILE_SUCCESS: 'CREATE_ATTACH_FILE_SUCCESS',
  CREATE_ATTACH_FILE_FAILED: 'CREATE_ATTACH_FILE_FAILED',
  CREATE_ATTACH_FILE_INITIAL_STATE: 'CREATE_ATTACH_FILE_INITIAL_STATE',
};

export const GET_ATTACH_FILE = {
  GET_ATTACH_FILE_REQUEST: 'GET_ATTACH_FILE_REQUEST',
  GET_ATTACH_FILE_SUCCESS: 'GET_ATTACH_FILE_SUCCESS',
  GET_ATTACH_FILE_FAILED: 'GET_ATTACH_FILE_FAILED',
};
