import * as yup from 'yup';
import { FORM_FIELDS } from '@constants/forms';

const DISTRICT_RESERVED_SEATS =
  FORM_FIELDS.ELECTION_SCHEDULE_MANAGEMENT.MAIN_LIST.DISTRICT_RESERVED_SEATS
    .CREATE_DISTRICT_RESERVED_SEATS;

export const districtReservedSeatsValidation = yup.object().shape({
  [DISTRICT_RESERVED_SEATS.RMO]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.RMO'),
  [DISTRICT_RESERVED_SEATS.DIVISION]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.DIVISION'),
  [DISTRICT_RESERVED_SEATS.DISTRICT]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.DISTRICT'),
  [DISTRICT_RESERVED_SEATS.RESERVED_WARD_NO]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.RESERVED_WARD_NO'),
  [DISTRICT_RESERVED_SEATS.RESERVED_WARD_BN]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.RESERVED_WARD_BN'),
  [DISTRICT_RESERVED_SEATS.RESERVED_WARD_EN]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.RESERVED_WARD_EN'),
  [DISTRICT_RESERVED_SEATS.INCLUSION_1]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.INCLUSION_1'),
  [DISTRICT_RESERVED_SEATS.INCLUSION_2]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.INCLUSION_2'),
  [DISTRICT_RESERVED_SEATS.INCLUSION_3]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.INCLUSION_3'),
  [DISTRICT_RESERVED_SEATS.INCLUSION_4]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.INCLUSION_4'),
  [DISTRICT_RESERVED_SEATS.CONDITION]: yup
    .string()
    .required('DISTRICT_RESERVED_SEATS_ERROR_MSG.CONDITION'),
});

export type DistrictReservedSeatsDataType = yup.InferType<
  typeof districtReservedSeatsValidation
>;
