import { CANDIDATE_INFO } from '@constants/candidate-info';

export const candidateNameMapping = (
  candidateId: string | number | undefined,
) => {
  switch (candidateId) {
    case CANDIDATE_INFO.NATIONAL_MEMBER_OF_PARLIAMENT.ID:
      return CANDIDATE_INFO.NATIONAL_MEMBER_OF_PARLIAMENT.NAME;

    case CANDIDATE_INFO.UPAZILLA_CHAIRMAN.ID:
      return CANDIDATE_INFO.UPAZILLA_CHAIRMAN.NAME;

    case CANDIDATE_INFO.UPAZILLA_VICE_CHAIRMAN.ID:
      return CANDIDATE_INFO.UPAZILLA_VICE_CHAIRMAN.NAME;

    case CANDIDATE_INFO.UPAZILLA_WOMEN_VICE_CHAIRMAN.ID:
      return CANDIDATE_INFO.UPAZILLA_WOMEN_VICE_CHAIRMAN.NAME;

    case CANDIDATE_INFO.CITY_CORPORATION_MAYOR.ID:
      return CANDIDATE_INFO.CITY_CORPORATION_MAYOR.NAME;

    case CANDIDATE_INFO.CITY_CORPORATION_COUNCILLOR.ID:
      return CANDIDATE_INFO.CITY_CORPORATION_COUNCILLOR.NAME;

    case CANDIDATE_INFO.CITY_CORPORATION_WOMAN_COUNCILLOR.ID:
      return CANDIDATE_INFO.CITY_CORPORATION_WOMAN_COUNCILLOR.NAME;

    case CANDIDATE_INFO.UNION_PARISHAD_CHAIRMAN.ID:
      return CANDIDATE_INFO.UNION_PARISHAD_CHAIRMAN.NAME;

    case CANDIDATE_INFO.UNION_PARISHAD_GENERAL_MEMBER.ID:
      return CANDIDATE_INFO.UNION_PARISHAD_GENERAL_MEMBER.NAME;

    case CANDIDATE_INFO.UNION_PARISHAD_RESERVED_MEMBER.ID:
      return CANDIDATE_INFO.UNION_PARISHAD_RESERVED_MEMBER.NAME;

    case CANDIDATE_INFO.MUNICIPALITY_MAYOR.ID:
      return CANDIDATE_INFO.MUNICIPALITY_MAYOR.NAME;

    case CANDIDATE_INFO.MUNICIPALITY_COUNCILLOR.ID:
      return CANDIDATE_INFO.MUNICIPALITY_COUNCILLOR.NAME;

    case CANDIDATE_INFO.MUNICIPALITY_RESERVED_COUNCILLOR.ID:
      return CANDIDATE_INFO.MUNICIPALITY_RESERVED_COUNCILLOR.NAME;

    case CANDIDATE_INFO.NATIONAL_RESERVED_WOMAN_MEMBER_OF_PARLIAMENT.ID:
      return CANDIDATE_INFO.NATIONAL_RESERVED_WOMAN_MEMBER_OF_PARLIAMENT.NAME;

    case CANDIDATE_INFO.ZILLA_PARISHAD_CHAIRMAN.ID:
      return CANDIDATE_INFO.ZILLA_PARISHAD_CHAIRMAN.NAME;

    case CANDIDATE_INFO.ZILLA_PARISHAD_GENERAL_WARD_COUNCILLOR.ID:
      return CANDIDATE_INFO.ZILLA_PARISHAD_GENERAL_WARD_COUNCILLOR.NAME;

    case CANDIDATE_INFO.ZILLA_PARISHAD_RESERVED_WARD_COUNCILLOR.ID:
      return CANDIDATE_INFO.ZILLA_PARISHAD_RESERVED_WARD_COUNCILLOR.NAME;

    default:
      break;
  }
};
