import { ELECTION_INFO } from '@constants/election-info';

export const electionNameMapping = (electionId: number) => {
  switch (electionId) {
    case ELECTION_INFO.NATIONAL.ID:
      return ELECTION_INFO.NATIONAL.NAME;

    case ELECTION_INFO.UPAZILLA.ID:
      return ELECTION_INFO.UPAZILLA.NAME;

    case ELECTION_INFO.UNION_PARISHAD.ID:
      return ELECTION_INFO.UNION_PARISHAD.NAME;

    case ELECTION_INFO.CITY_CORPORATION.ID:
      return ELECTION_INFO.CITY_CORPORATION.NAME;

    case ELECTION_INFO.MUNICIPALITY.ID:
      return ELECTION_INFO.MUNICIPALITY.NAME;

    case ELECTION_INFO.PRESIDENT.ID:
      return ELECTION_INFO.PRESIDENT.NAME;

    case ELECTION_INFO.BY.ID:
      return ELECTION_INFO.BY.NAME;

    case ELECTION_INFO.NATIONAL_RESERVE_SEAT.ID:
      return ELECTION_INFO.NATIONAL_RESERVE_SEAT.NAME;

    case ELECTION_INFO.ZILLA_PARISHAD.ID:
      return ELECTION_INFO.ZILLA_PARISHAD.NAME;

    default:
      break;
  }
};
