import { FORM_FIELDS } from '@constants/forms';

const ASSET_LIABILITIES =
  FORM_FIELDS.CANDIDATE_INFO_MANAGEMENT.OPERATOR.ASSET_LIABILITIES;

export const ASSET_TYPE = {
  IMMOVABLE: 'IMMOVABLE',
  OTHER: 'OTHER',
  HOME: 'HOME',
};

export const FIELD_ARRAY_TYPE = {
  ASSETS_EXCEPT_HOUSE: 'assetsExceptHouse',
  HOUSE_ASSETS: 'houseAssets',
  OTHERS_ASSETS: 'othersAssets',
  YEARLY_INCOME: 'yearlyIncomesAndExpenditures',
};

export const assetsExceptHouseDefaultValues = {
  [ASSET_LIABILITIES.TOTAL_AMOUNT]: '',
  [ASSET_LIABILITIES.OTHER_LOCATION]: '',
  [ASSET_LIABILITIES.OTHER_ESTIMATED_VALUE]: '',
};

export const houseAssetDefaultValues = {
  [ASSET_LIABILITIES.HOUSE_NATURE_AND_NUMBER]: '',
  [ASSET_LIABILITIES.HOUSE_LOCATION]: '',
  [ASSET_LIABILITIES.HOUSE_ESTIMATED_VALUE]: '',
};

export const otherAssetDefaultValues = {
  [ASSET_LIABILITIES.OTHER_ASSETS]: '',
  [ASSET_LIABILITIES.OTHER_ASSETS_ESTIMATED_VALUE]: '',
};

export const yearlyIncomeSpendingDefaultValues = {
  [ASSET_LIABILITIES.TOTAL_ESTIMATED_ANNUAL_INCOME]: '',
  [ASSET_LIABILITIES.TOTAL_ESTIMATED_ANNUAL_COST]: '',
};
