export const CANDIDATE_INFO_MANAGEMENT = {
  // Controller List
  CONTROLLER_LIST: {
    // Candidate Management
    CANDIDATE_MANAGEMENT: {
      SEARCH_NID_OR_Name: 'candidateNameOrNid',
      SEND_SMS_MODAL: {
        USER_ID: 'userId',
        NEW_PASSWORD: 'newPassword',
      },
      UPDATE_PROFILE: {
        USER_NAME: 'username',
        EMAIL: 'email',
        PHONE: 'phone',
      },
      CANDIDATE_NOMINATION_DASHBOARD_FORM: {
        ATTACHMENT: {},
        PROPOSER: {
          NAME: 'name',
          VOTER_NO: 'voterNo',
          NID_NUMBER: 'nid',
          ID: 'id',
          REGION_ID: 'regionId',
          DISTRICT: 'zillaName',
          ELECTION_SEAT: 'constituencyName',
          SUB_DISTRICT: 'upazilaName',
          RMO: 'rmoName',
          MUNICIPALITY: 'municipalityId',
          MUNICIPALITY_NAME: 'municipalityName',
          UNION: 'unionOrWardName',
          VOTER_AREA: 'voterAreaName',
          CANDIDATE_NAME: 'name',
          CANDIDATE_ADDRESS: 'candidateAddress',
          ELECTION_AREA_NAME: 'constituencyName',
          POST_NAME: 'candidateTypeName',
          SERIAL_NUMBER: 'serialNo',
        },
        SUPPORTER: {
          NAME: 'name',
          VOTER_NO: 'voterNo',
          NID_NUMBER: 'nid',
          SERIAL_NUMBER: 'serialNo',
          REGION_ID: 'regionId',
          DISTRICT: 'zillaName',
          ELECTION_SEAT: 'constituencyName',
          SUB_DISTRICT: 'upazilaName',
          RMO: 'rmoName',
          MUNICIPALITY: 'municipalityId',
          UNION: 'unionOrWardName',
          VOTER_AREA: 'voterAreaName',
          ELECTION_AREA_NAME: 'electionAreaName',
          CONSTITUENCY: 'constituencyName',
          CANDIDATE_NAME: 'candidateName',
          CANDIDATE_ADDRESS: 'candidateAddress',
          ID: 'serialNo',

          CANDIDATE_ELECTION_DETAILS: {
            CANDIDATE_TYPE: 'candidateTypeName',
            NAME: 'name',
            ADDRESS: 'candidateAddress',
            VOTER_NUMBER: 'voterNo',
            ZILLA: 'zillaName',
            CONSTITUENCY: 'constituencyName',
          },
        },
        NOMINATED_CANDIDATE: {
          CANDIDATE_NAME: 'name',
          NID: 'nid',
          FATHER_NAME: 'fatherOrHusbandName',
          MOTHER_NAME: 'motherName',
          SERIAL_NUMBER: 'serialNo',
          ID: 'id',
          DIVISION: 'regionName',
          DISTRICT: 'zillaName',
          SUB_DISTRICT: 'upazilaName',
          RMO: 'rmoName',
          UNION: 'unionOrWardName',
          VOTER_AREA_NAME: 'voterAreaName',
          ADDRESS: 'candidateAddress',
          VOTER_NO: 'voterNo',
          BANK_ACCOUNT_NO: 'bankAccountNo',
          BANK_NAME: 'bankName',
          BRANCH_NO: 'bankBranchName',
          INCOME_TAX: 'incomeTax',
          TIN: 'tin',

          POLITICAL_PARTY_ID: 'politicalPartyId',
          POLITICAL_PARTY_NAME: 'politicalPartyName',
          POLITICAL_PARTY_SYMBOL_NAME: 'symbolName',
          PREFERRED_SYMBOL_ID: 'preferredSymbolId',
          PREFERRED_SYMBOL_NAME: 'preferredSymbolName',
        },
        COLLATERAL: {
          MANUAL_PAYMENT: {
            CHALAN_NO: 'chalanNumber',
            CHALAN_DATE: 'chalanDate',
            DEPOSIT_TYPE: 'depositedIn',
            ZILLA: 'zilla',
            REGION: 'region',
            REGION_ID: 'regionId',
            BANK: 'bank',
            BANK_ID: 'bankId',
            BRANCH_NAME: 'branchName',
            FILE: 'file',
          },
          SPG_PAYMENT: {
            TRAN_ID: 'tranId',
            COMMISSION: 'commission',
            TOTAL_AMOUNT: 'totalAmount',
            STATUS: 'status',
            TRAN_DATE: 'tranDate',
          },
          SSL_PAYMENT: {
            BANK_TRAN_ID: 'bankTranId',
            STORE_AMOUNT: 'storeAmount',
            AMOUNT: 'amount',
            STATUS: 'status',
            TRAN_DATE: 'tranDate',
            CARD_NO: 'cardNo',
            CARD_TYPE: 'cardType',
          },
          A_CHALAN_PAYMENT: {
            CHALAN_NO: 'challanNo',
            PAYMENT_ID: 'paymentId',
            PAID_AMOUNT: 'paidAmount',
            STATUS: 'status',
            PAYMENT_DATE: 'paymentDate',
          },
        },
      },
    },

    // Candidate Applied Online
    CANDIDATE_APPLIED_ONLINE: {
      ACKNOWLEDGEMENT_RECEIPT: {
        SERIAL_NUMBER: 'candidateSerial',
        CONSTITUENCY: 'candidateLocation',
        CANDIDATE_NAME: 'candidateName',
        NOMINATION_SUBMISSION_DATE: 'finalSubmissionDate',
        SUBMITTED_BY: 'proposedBy',
        NOMINATION_SELECTION_DATE: 'ROSelectedDate',
        NOMINATION_SELECTION_PLACE: 'ROSelectedPlace',
        REMARK: 'comments',
        UPLOAD_DOCUMENT: 'file',
      },

      NOMINATION_ACCEPTANCE_DECISION: {
        ACCEPT_NOMINATION_LETTER: 'nominationStatusId',
        REMARK: 'comments',
        UPLOAD_DOCUMENT: 'file',
      },
    },

    // Appeal
    APPEAL: {
      APPEAL_TABLE: {
        APPEAL_TYPE: 'appealType',
        DETAILS: 'details',
        FILE: 'file',
      },
    },

    // Symbol Allocation
    SYMBOL_ALLOCATION: {
      ALLOCATION_TABLE: {
        ALLOCATED_SYMBOL: 'symbolId',
        CANDIDATE_NAME_SERIAL: 'candidateSerial',
      },
    },

    // Candidate Confirmation
    CANDIDATE_CONFIRMATION: {
      NOMINATION: {
        PROPOSER: {
          NAME: 'name',
          VOTER_NUMBER: 'voterNo',
          NID_NUMBER: 'nid',
          SERIAL_NUMBER: 'serialNo',
          ZILLA: 'zillaName',
          CONSTITUENCY: 'constituencyName',
          UPAZILA: 'upazilaName',
          RMO: 'rmoName',
          MUNICIPALITY: 'municipalityName',
          UNION_OR_WARD: 'unionOrWardName',
          UP_WARD: 'unionWardName',
          VOTER_AREA: 'voterAreaName',
          CANDIDATE_ELECTION_DETAILS: {
            CANDIDATE_TYPE: 'candidateTypeName',
            NAME: 'name',
            ADDRESS: 'candidateAddress',
            VOTER_NUMBER: 'voterNo',
            ZILLA: 'zillaName',
            CONSTITUENCY: 'constituencyName',
            MUNICIPALITY: 'municipalityName',
          },
        },
        SUPPORTER: {
          NAME: 'name',
          VOTER_NUMBER: 'voterNo',
          NID_NUMBER: 'nid',
          SERIAL_NUMBER: 'serialNo',
          ZILLA: 'zillaName',
          CONSTITUENCY: 'constituencyName',
          UPAZILA: 'upazilaName',
          MUNICIPALITY: 'municipalityName',
          RMO: 'rmoName',
          UNION_OR_WARD: 'unionOrWardName',
          UP_WARD: 'unionWardName',
          VOTER_AREA: 'voterAreaName',
          CANDIDATE_ELECTION_DETAILS: {
            CANDIDATE_TYPE: 'candidateTypeName',
            NAME: 'name',
            ADDRESS: 'candidateAddress',
            VOTER_NUMBER: 'voterNo',
            ZILLA: 'zillaName',
            CONSTITUENCY: 'constituencyName',
            MUNICIPALITY: 'municipalityName',
          },
        },
        NOMINATED_CANDIDATE: {
          NAME: 'name',
          NID_NO: 'nid',
          FATHER_OR_HUSBAND_NAME: 'fatherOrHusbandName',
          MOTHER_NAME: 'motherName',
          SERIAL_NUMBER: 'serialNo',
          REGION: 'regionName',
          ZILLA: 'zillaName',
          UPAZILA: 'upazilaName',
          RMO: 'rmoName',
          UNION_OR_WARD: 'unionOrWardName',
          UP_WARD: 'unionWardName',
          VOTER_AREA: 'voterAreaName',
          VOTER_NO: 'voterNo',
          PERMANENT_ADDRESS: 'candidateAddress',
          BANK_ACCOUNT_NO: 'bankAccountNo',
          BANK: 'bankName',
          BANK_BRANCH_NAME: 'bankBranchName',
          TIN: 'tin',

          POLITICAL_PARTY_ID: 'politicalPartyId',
          POLITICAL_PARTY_NAME: 'politicalPartyName',
          POLITICAL_PARTY_SYMBOL_NAME: 'symbolName',
          PREFERRED_SYMBOL_ID: 'preferredSymbolId',
          PREFERRED_SYMBOL_NAME: 'preferredSymbolName',
        },
        ANNOUNCEMENT: {
          IS_ELECTED_BEFORE: 'isElectedBefore',
          CANDIDATE_PAST_ELECTION_INFO: {
            PAST_ELECTION_NAME: 'pastElectionName',
            PAST_ELECTION_INFO: 'pastElectionInfo',
          },
          CANDIDATE_PRESENT_ELECTION_INFO: {
            CONSTITUENCY: 'constituencyName',
          },
        },
      },
      PERSONAL: {
        PERSONAL_INFO: {
          CANDIDATE_NAME: 'name',
          CANDIDATE_NAME_EN: 'nameEn',
          NATIONAL_ID: 'nid',
          FATHER_NAME: 'fatherName',
          FATHER_NAME_EN: 'fatherNameEn',
          MOTHER_NAME: 'motherName',
          MOTHER_NAME_EN: 'motherNameEn',
          SPOUSE_NAME: 'spouseName',
          SPOUSE_NAME_EN: 'spouseNameEn',
          DATE_OF_BIRTH: 'dob',
          AGE: 'age',
          PLACE_OF_BIRTH: 'birthPlaceZillaId',
          ADDRESS_OF_PLACE_OF_BIRTH: 'birthPlaceAddress',
          GENDER: 'gender',
          MARITAL_STATUS: 'maritalStatus',
          OCCUPATION: 'occupation',
          SPOUSE_OCCUPATION: 'spouseOccupation',
          CANDIDATE_TIN_NUMBER: 'tin',
        },
        ADDRESS: {
          PERMANENT_ADDRESS: 'permanentAddress',
          PRESENT_ADDRESS: 'presentAddress',
        },
        EMERGENCY_CONTACT: {
          TELEPHONE_NUMBER: 'telephone',
          MOBILE_NUMBER: 'phone',
          EMAIL_ADDRESS: 'email',
        },
        CURRENT_WORKPLACE: {
          WORKPLACE_NAME: 'officeName',
          WORKPLACE_ADDRESS: 'occupationalAddress',
        },
        CHILDREN: {
          IDX: 'idx',
          NAME: 'name',
          EDUCATIONAL_QUALIFICATION: 'education',
          DATE_OF_BIRTH: 'dob',
          INSTITUTE_ADDRESS: 'occupationAndOfficeAddress',
          MARITAL_STATUS: 'maritalStatus',
        },
        DATE: 'date',
      },
      AFFIDAVIT: {
        AFFIDAVIT: {
          DATE_OF_BIRTH: 'dob',
          CANDIDATE_ADDRESS: 'address',
          PRESENT_ADDRESS: 'presentAddress',
          PERMANENT_ADDRESS: 'permanentAddress',
          CANDIDATES_HIGHER_DEGREE: 'educationalQualification',
          CANDIDATE_NAME: 'name',
          CASE_NUMBER: 'caseNumber',
          CASE_STATUS: 'caseStatus',
          COURT_NAME: 'courtName',
          NO_PRESENT_CRIMINAL_CASE: 'noPresentCriminalCase',
          FATHER_OR_HUSBAND_NAME: 'fatherName',
          FATHER_HUSBAND_NAME: 'fatherOrHusbandName',
          CASE_FILE: 'caseFile',
          ACCUSED_CASE: 'accusedCase',
          CASE_TYPE: 'caseType',
          MOTHER_NAME: 'motherName',
          OCCUPATION: 'occupationDescription',
          NO_PAST_CRIMINAL_CASE_BEFORE: 'noPastCriminalCase',
          ID: 'id',
          AGRICULTURE_DEPENDENT_EARNING_SOURCE:
            'agricultureDependentEarningSource',
          HOUSE_OTHERS_DEPENDENT_EARNING_SOURCE:
            'houseOthersDependentEarningSource',
          BUSINESS_DEPENDENT_EARNING_SOURCE: 'businessDependentEarningSource',
          SONCHOYPOTRO_BANK_DEPENDENT_EARNING_SOURCE:
            'sonchoypotroBankDependentEarningSource',
          OCCUPATION_TEACHER_DEPENDENT_EARNING_SOURCE:
            'ocuupationTeacherDependentEarningSource',
          JOB_DEPENDENT_EARNING_SOURCE: 'jobDependentEarningSource',
          OTHERS_DEPENDENT_EARNING_SOURCE: 'othersDependentEarningSource',
          AGRICULTURE_YEARLY_INCOME: 'agricultureYearlyIncome',
          HOUSE_OTHERS_YEARLY_INCOME: 'houseOthersYearlyIncome',
          BUSINESS_YEARLY_INCOME: 'businessYearlyIncome',
          SONCHOYPOTRO_BANK_YEARLY_INCOME: 'sonchoypotroBankYearlyIncome',
          OCCUPATION_TEACHER_YEARLY_INCOME: 'ocuupationTeacherYearlyIncome',
          JOB_YEARLY_INCOME: 'jobYearlyIncome',
          OTHERS_YEARLY_INCOME: 'othersYearlyIncome',
        },
      },
      LIABILITY_LOAN_OATH: {
        NOT_ELECTED_BEFORE: 'notElectedBefore',
        NOT_RECEIVED_LOANS: 'notReceivedLoans',
        LIABILITIES: {
          NATURE_LIABILITIES_DEBTS: 'natureLiabilitiesDebts',
          AMOUNT: 'amount',
          FILE: 'file',
        },
        COMMITMENT_ACHIEVEMENTS: {
          PROMISES: 'promises',
          ACHIEVEMENTS: 'achievements',
        },
        OATH: {
          HOLOFNAMA_SUBMISSION_DATE: 'holofnamaSubmissionDate',
          MAGISTRATE_NOTARY_PUBLIC: {
            NAME: 'name',
            SIGNING_DATE: 'signingDate',
          },
          IDENTIFIER_INFO: {
            NAME: 'name',
            ADDRESS: 'address',
          },
          CANDIDATE_INFO: {
            NAME: 'name',
            FATHER_INFO: 'fatherName',
            FATHER_OR_HUBAND_NAME: 'fatherOrHusbandName',
            SPOUSE_NAME: 'spouseName',
            MOTHER_NAME: 'motherName',
            ADDRESS: 'address',
          },
        },
      },
    },

    // Candidacy Withdrawal
    CANDIDACY_WITHDRAWAL: {
      WITHDRAWAL_TABLE: {
        DETAILS: 'comments',
        ATTACHMENT: 'file',
      },
    },

    // Selection
    SELECTION: {
      TABLE: {
        INFO: 'selectionTableInfo',
        REASON: 'comments',
        FILE: 'file',
      },
    },

    // Candidate Verify
    CANDIDATE_VERIFY: {
      VIEW_CANDIDATE_VERIFY: {
        IS_CANDIDATE_INFO_CORRECT: 'isCandidateInfoCorrect',
        IS_PROPOSER_INFO_CORRECT: 'isProposerInfoCorrect',
        IS_VERIFIER_INFO_CORRECT: 'isVerifierInfoCorrect',
        IS_CANDIDATE_PERSONAL_INFO_CORRECT: 'isCandidatePersonalInfoCorrect',
        IS_HALAFNAMA_CORRECT: 'isHalafnamaCorrect',
        IS_ATTACHMENT_CORRECT: 'isAttachmentCorrect',
        IS_CANDIDATE_AGE_CORRECT: 'isCandidateAgeCorrect',
        IS_CANDIDATE_VOTER_NO_CORRECT: 'isCandidateVoterNoCorrect',
        IS_PROPOSER_VOTER_NO_CORRECT: 'isProposerVoterNoCorrect',
        IS_SUPPORTER_VOTER_NO_CORRECT: 'isSupporterVoterNoCorrect',
        COMMENT: 'comment',
      },
    },

    // Report
    REPORT: {
      CONTENDING_CANDIDATES_NUMBER: {
        ELECTION_TYPE: 'electionType',
        ELECTION_NAME: 'electionName',
        CANDIDATE_TYPE: 'candidateType',
        DISTRICT: 'district',
        SEAT: 'seat',
      },

      NOMINATION_PAPER_INFORMATION: {
        ELECTION_TYPE: 'nominationPaperElectionType',
        ELECTION_NAME: 'nominationPaperElectionName',
        CANDIDATE_TYPE: 'nominationPaperCandidateType',
        DISTRICT: 'nominationPaperDistrict',
        SEAT: 'nominationPaperSeat',
      },

      CONTESTING_CANDIDATES_MODAL: {
        VOTER_COUNT: 'voterCount',
      },
    },
  },

  // Operator
  OPERATOR: {
    NOMINATION_FORM: {
      FIRST_PART: {
        SUPPORTER: {
          IS_AGREE: 'isAgree',
          ID: 'id',
          NID_NUMBER: 'nid',
          NOMINEE_NAME: 'name',
          SERIAL_NUMBER: 'serialNo',
          DISTRICT_NAME: 'districtName',
          CONSTITUENCY: 'constituencyId',
          UPAZILA: 'upazilaId',
          MUNICIPALITY: 'municipality',
          UNION: 'unionOrWardId',
          VOTER_AREA: 'voterAreaId',
        },
        CANDIDATE: {
          CANDIDATE_ID: 'candidateTypeId',
          CANDIDATE_NAME: 'name',
          CANDIDATE_ADDRESS: 'candidateAddress',
          CANDIDATE_VOTER_NUMBER: 'voterNo',
          CANDIDATE_DISTRICT_NAME: 'districtName',
          CANDIDATE_CONSTITUENCY: 'constituencyId',
          CANDIDATE_POST_NAME: 'postName',
        },

        // --- ONS
        CANDIDATE_ELECTION_DETAILS: {
          CANDIDATE_ID: 'candidateTypeId',
          NAME: 'name',
          ADDRESS: 'candidateAddress',
          VOTER_NUMBER: 'voterNo',
          ZILLA_ID: 'zillaId',
          CONSTITUENCY_ID: 'constituencyId',
          CONSTITUENCY_NAME: 'constituencyName',
          MUNICIPALITY_NAME: 'municipalityName',
        },

        // --- ONS
        PROPOSER: {
          IS_AGREE: 'isAgree',
          ID: 'id',
          NAME: 'name',
          VOTER_NUMBER: 'voterNo',
          BIRTH_DATE: 'dob',
          NID_NUMBER: 'nid',
          ID_TYPE: 'idType',
          SERIAL_NUMBER: 'serialNo',
          ZILLA_ID: 'zillaId',
          CONSTITUENCY_ID: 'constituencyId',
          UPAZILA_ID: 'upazilaId',
          RMO_EN: 'rmoEn',
          MUNICIPALITY: 'municipalityId',
          REGION_ID: 'regionId',
          UNION_OR_WARD_ID: 'unionOrWardId',
          UP_WARD_ID: 'unionWardId',
          VOTER_AREA_ID: 'voterAreaId',
        },
      },
      SECOND_PART: {
        SUPPORTER: {
          // shafe
          IS_AGREE: 'isAgree',
          ID: 'id',
          SUPPORTER_NID: 'nid',
          SUPPORTER_NAME: 'name',
          SERIAL_NUMBER: 'serialNo',
          DISTRICT_NAME: 'districtName',
          CONSTITUENCY: 'constituency',
          UPAZILA: 'upazila',
          RMO: 'rmo',
          UNION: 'union',
          VOTER_AREA: 'voterArea',

          // ons
          NAME: 'name',
          VOTER_NUMBER: 'voterNo',
          ID_TYPE: 'idType',
          NID_NUMBER: 'nid',
          BIRTH_DATE: 'dob',
          REGION_ID: 'regionId',
          ZILLA_ID: 'zillaId',
          CONSTITUENCY_ID: 'constituencyId',
          UPAZILA_ID: 'upazilaId',
          RMO_EN: 'rmo',
          MUNICIPALITY: 'municipalityId',
          UNION_OR_WARD_ID: 'unionOrWardId',
          UP_WARD_ID: 'unionWardId',
          VOTER_AREA_ID: 'voterAreaId',
        },
      },
      THIRD_PART: {
        CANDIDATE_PERSONAL_INFO: {
          // NAME: 'name',
          // NID_NO: 'nid',
          // FATHER_OR_HUSBAND_NAME: 'fatherOrHusbandName',
          // MOTHER_NAME: 'motherName',
          // PERMANENT_ADDRESS: 'permanentAddress',
          PRESENT_ADDRESS: 'presentAddress',
          // VOTER_NUMBER: 'voterNo',
          // SERIAL_NUMBER: 'serialNo',
          DEPARTMENT_NAME: 'departmentName',
          DISTRICT_NAME: 'districtName',
          UPAZILA: 'upazila',
          RMO: 'rmo',
          UNION: 'unionOrWard',
          VOTER_AREA: 'voterArea',
          // BANK_ACCOUNT_NO: 'bankAccountNo',
          BANK_NAME: 'bankName',
          BRANCH_NAME: 'bankBranchName',
          RADIO: 'radio',
          ME: 'me',
          POLITICAL_GROUP: 'politicalParty',

          // ons
          NAME: 'name',
          NID_NO: 'nid',
          FATHER_OR_HUSBAND_NAME: 'fatherOrHusbandName',
          MOTHER_NAME: 'motherName',
          PERMANENT_ADDRESS: 'candidateAddress',
          VOTER_NUMBER: 'voterNo',
          SERIAL_NUMBER: 'serialNo',
          REGION_ID: 'regionId',
          ZILLA_ID: 'zillaId',
          UPAZILA_ID: 'upazilaId',
          RMO_EN: 'rmo',
          MUNICIPALITY: 'municipalityId',
          UNION_OR_WARD_ID: 'unionOrWardId',
          UP_WARD_ID: 'unionWardId',
          VOTER_AREA_ID: 'voterAreaId',
          BANK_ACCOUNT_NO: 'bankAccountNo',
          BANK_ID: 'bankId',
          BANK_BRANCH_NAME: 'bankBranchName',
          TIN_NUMBER: 'tin',
        },

        CANDIDATE_POLITICAL_INFO: {
          POLITICAL_PARTY_CHECKBOX: 'politicalPartyCheckbox',
          POLITICAL_PARTY_ID: 'politicalPartyId',
          POLITICAL_PARTY_NAME: 'politicalPartyName',
          POLITICAL_PARTY_SYMBOL_NAME: 'symbolName',
          PREFERRED_SYMBOL_ID: 'preferredSymbolId',
          PREFERRED_SYMBOL_NAME: 'preferredSymbolName',
        },
      },
      FOURTH_PART: {
        IS_ELECTED_BEFORE: 'isElectedBefore',
        CANDIDATE_PAST_ELECTION_INFO: {
          CANDIDATE_NAME: 'name',
          DISTRICT_NAME: 'district',
          CONSTITUENCY: 'constituency',
          CONSTITUENCY_NUMBER_NAME: 'constituencyNumberName',
          CONSTITUENCY_AREA: 'constituencyArea',
          PAST_ELECTION_NAME: 'pastElectionName',
          PAST_ELECTION_INFO: 'pastElectionInfo',
        },
        CANDIDATE_PRESENT_ELECTION_INFO: {
          CONSTITUENCY_ID: 'constituencyId',
        },
      },

      ADD_NEW_NOMINATION: {
        PERSONAL: {
          NID: 'nid',
          NAME: 'name',
          BIRTH_DATE: 'dob',
          MOBILE: 'phone',
          EMAIL: 'email',
          GENDER: 'gender',
        },
        NOMINATION: {
          TYPE: 'electionTypeId',
          NAME: 'electionScheduleId',
          POST: 'post',
          DEPARTMENT: 'regionId',
          DISTRICT: 'zillaId',
          CONSTITUENCY: 'constituency',
          MUNICIPALITY: 'municipality',
          UPAZILLA: 'upazilla',
          UNION_WARD: 'unionOrWardsId',
        },
      },
    },

    CANDIDATE: {
      PERSONAL_INFO: {
        CANDIDATE_NAME: 'name',
        CANDIDATE_NAME_EN: 'nameEn',
        NATIONAL_ID: 'nid',
        FATHER_NAME: 'fatherName',
        FATHER_NAME_EN: 'fatherNameEn',
        MOTHER_NAME: 'motherName',
        MOTHER_NAME_EN: 'motherNameEn',
        SPOUSE_NAME: 'spouseName',
        SPOUSE_NAME_EN: 'spouseNameEn',
        DATE_OF_BIRTH: 'dob',
        AGE: 'age',
        PLACE_OF_BIRTH: 'birthPlaceZillaId',
        ADDRESS_OF_PLACE_OF_BIRTH: 'birthPlaceAddress',
        GENDER: 'gender',
        MARITAL_STATUS: 'maritalStatus',
        OCCUPATION: 'occupation',
        SPOUSE_OCCUPATION: 'spouseOccupation',
        CANDIDATE_TIN_NUMBER: 'tin',
      },
      ADDRESS: {
        PERMANENT_ADDRESS: 'permanentAddress',
        PRESENT_ADDRESS: 'presentAddress',
      },
      EMERGENCY_CONTACT: {
        TELEPHONE_NUMBER: 'telephone',
        MOBILE_NUMBER: 'phone',
        EMAIL_ADDRESS: 'email',
      },
      CURRENT_WORKPLACE: {
        WORKPLACE_NAME: 'officeName',
        WORKPLACE_ADDRESS: 'occupationalAddress',
      },
      CHILDREN: {
        IDX: 'idx',
        NAME: 'childName',
        EDUCATIONAL_QUALIFICATION: 'education',
        DATE_OF_BIRTH: 'childDob',
        INSTITUTE_ADDRESS: 'occupationAndOfficeAddress',
        MARITAL_STATUS: 'childMaritalStatus',
      },
      DATE: 'date',
    },

    ATTACH_FILE: {
      CANDIDATE_IMAGE: 'candidateImage',
      AFFIDAVIT: 'candidateHalafnama',
      POLITICAL_PARTY_NOMINATION: 'candidatePoliticalNomination',
      INCOME_TAX_RETURN_COPY: 'candidateIncomeTax',
      VOTERS_SUPPORT_SIGNED_LIST: 'candidateSupporters',
      CANDIDATE_EXPENDITURE: 'candidateExpenditure',
      HIGHEST_EDUCATIONAL_QUALIFICATION: 'candidateEducationalCertificate',
      UTILITY_BILL: 'candidateUtilityBill',
      BUY_CD: 'candidateVoterListReceipt',
      OTHER_DOCUMENTS: 'candidateOthers',
      DOCUMENT: {
        DOCUMENT_ID: 'documentId',
        FILE_ID: 'fileId',
        FILE_NAME: 'filename',
        FILE_TYPE: 'fileType',
      },
    },

    AFFIDAVIT: {
      FIRST_STEP: {
        DATE_OF_BIRTH: 'dob',
        CANDIDATE_ADDRESS: 'address',
        PRESENT_ADDRESS: 'presentAddress',
        PERMANENT_ADDRESS: 'permanentAddress',
        CANDIDATES_HIGHER_DEGREE: 'educationalQualification',
        CANDIDATE_NAME: 'name',
        CASE_NUMBER: 'caseNumber',
        CASE_STATUS: 'caseStatus',
        COURT_NAME: 'courtName',
        NO_PRESENT_CRIMINAL_CASE: 'noPresentCriminalCase',
        FATHER_HUSBAND_NAME: 'fatherOrHusbandName',
        CASE_FILE: 'caseFile',
        ACCUSED_CASE: 'accusedCase',
        CASE_TYPE: 'caseType',
        MOTHER_NAME: 'motherName',
        OCCUPATION: 'occupationDescription',
        NO_PAST_CRIMINAL_CASE_BEFORE: 'noPastCriminalCase',
        ID: 'id',
        AGRICULTURE_DEPENDENT_EARNING_SOURCE:
          'agricultureDependentEarningSource',
        HOUSE_OTHERS_DEPENDENT_EARNING_SOURCE:
          'houseOthersDependentEarningSource',
        BUSINESS_DEPENDENT_EARNING_SOURCE: 'businessDependentEarningSource',
        SONCHOYPOTRO_BANK_DEPENDENT_EARNING_SOURCE:
          'sonchoypotroBankDependentEarningSource',
        OCCUPATION_TEACHER_DEPENDENT_EARNING_SOURCE:
          'ocuupationTeacherDependentEarningSource',
        JOB_DEPENDENT_EARNING_SOURCE: 'jobDependentEarningSource',
        OTHERS_DEPENDENT_EARNING_SOURCE: 'othersDependentEarningSource',
        AGRICULTURE_YEARLY_INCOME: 'agricultureYearlyIncome',
        HOUSE_OTHERS_YEARLY_INCOME: 'houseOthersYearlyIncome',
        BUSINESS_YEARLY_INCOME: 'businessYearlyIncome',
        SONCHOYPOTRO_BANK_YEARLY_INCOME: 'sonchoypotroBankYearlyIncome',
        OCCUPATION_TEACHER_YEARLY_INCOME: 'ocuupationTeacherYearlyIncome',
        JOB_YEARLY_INCOME: 'jobYearlyIncome',
        OTHERS_YEARLY_INCOME: 'othersYearlyIncome',
      },
      LIABILITY_LOAN_OATH: {
        NOT_ELECTED_BEFORE: 'notElectedBefore',
        NOT_RECEIVED_LOANS: 'notReceivedLoans',
        LIABILITIES: {
          NATURE_LIABILITIES_DEBTS: 'natureLiabilitiesDebts',
          AMOUNT: 'amount',
          FILE: 'file',
        },
        COMMITMENT_ACHIEVEMENTS: {
          PROMISES: 'promises',
          ACHIEVEMENTS: 'achievements',
        },
        OATH: {
          HOLOFNAMA_SUBMISSION_DATE: 'holofnamaSubmissionDate',
          MAGISTRATE_NOTARY_PUBLIC: {
            NAME: 'name',
            SIGNING_DATE: 'signingDate',
          },
          IDENTIFIER_INFO: {
            NAME: 'name',
            ADDRESS: 'address',
          },
          CANDIDATE_INFO: {
            NAME: 'name',
            FATHER_NAME: 'fatherName',
            FATHER_OR_HUSBAND_NAME: 'fatherOrHusbandName',
            MOTHER_NAME: 'motherName',
            ADDRESS: 'address',
          },
        },
      },
    },
    ASSET_LIABILITIES: {
      ELECTION_AREA_NAME_NUMBER: 'constituencyNameAndNo',
      CANDIDATE_NAME: 'candidateName',
      CANDIDATE_ADDRESS: 'candidateAddress',

      TOTAL_AMOUNT: 'totalAmount',
      OTHER_LOCATION: 'position',
      OTHER_ESTIMATED_VALUE: 'approximatePrice',

      HOUSE_NATURE_AND_NUMBER: 'homeTypeAndNo',
      HOUSE_LOCATION: 'position',
      HOUSE_ESTIMATED_VALUE: 'approximatePrice',

      OTHER_ASSETS: 'otherAssetsName',
      OTHER_ASSETS_ESTIMATED_VALUE: 'approximatePrice',

      TOTAL_ESTIMATED_ANNUAL_INCOME: 'totalApproximateIncome',
      TOTAL_ESTIMATED_ANNUAL_COST: 'totalApproximateExpenditure',
    },

    // income source details
    INCOME_SOURCE_DETAILS: {
      BASIC_INFO: {
        CONSTITUENCY_NAME_AND_NUMBER: 'constituencyNameAndNo',
        CANDIDATE_NAME: 'candidateName',
        CANDIDATE_ADDRESS: 'candidateAddress',
      },
      EARNING_FROM_OWN_INCOME: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        EARNING_SOURCE: 'incomeSource',
      },
      EARNING_FROM_RELATIVES: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        RELATIVE_NAME: 'relativeName',
        RELATIVE_ADDRESS: 'relativeAddress',
        RELATION: 'relation',
        RELATIVE_INCOME_SOURCE: 'relativeIncomeSource',
        RELATIVE_FUNDING_TYPE: 'relativeFundingType',
      },
      EARNING_FROM_DONATION_BY_RELATIVES: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        RELATIVE_NAME: 'relativeName',
        RELATIVE_ADDRESS: 'relativeAddress',
        RELATION: 'relation',
        RELATIVE_INCOME_SOURCE: 'relativeIncomeSource',
        RELATIVE_FUNDING_TYPE: 'relativeFundingType',
      },
      EARNING_FROM_OTHERS: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        PERSON_NAME: 'personOrInstitutionName',
        PERSON_ADDRESS: 'personOrInstitutionAddress',
        INCOME_SOURCE: 'incomeSource',
        FUNDING_TYPE: 'otherFundingType',
      },
      EARNING_FROM_DONATION_BY_OTHERS: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        PERSON_NAME: 'personOrInstitutionName',
        PERSON_ADDRESS: 'personOrInstitutionAddress',
        INCOME_SOURCE: 'incomeSource',
        FUNDING_TYPE: 'otherFundingType',
      },
      EARNING_FROM_MISCELLANEOUS: {
        POTENTIAL_AMOUNT: 'approximateAmount',
        PERSON_OR_INSTITUTE_NAME: 'personOrInstitutionName',
        PERSON_OR_INSTITUTE_ADDRESS: 'personOrInstitutionAddress',
        PERSON_OR_INSTITUTE_INCOME_SOURCE: 'incomeSource',
        FUNDING_TYPE: 'otherFundingType',
      },
      POSTER_EXPENSE: {
        APPROXIMATE_NUMBER_OF_POSTER: 'approximateNumberOfPoster',
        APPROXIMATE_TOTAL_COST: 'approximateTotalCost',
      },
      ELECTION_OFFICE_EXPENSE: {
        POSSIBLE_NUMBER_OF_OFFICE: 'possibleNumberOfOffice',
        POSSIBLE_COST_OF_OFFICE: 'possibleCostOfOffice',
        POSSIBLE_COST_OF_OFFICE_STUFF: 'possibleCostOfOfficeStuff',
      },
      CANDIDATE_CENTRAL_OFFICE_EXPENSE: {
        POSSIBLE_COST_OF_CONSTRUCTION: 'possibleCostOfConstruction',
        POSSIBLE_COST_OF_STUFF: 'possibleCostOfStuff',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      CANDIDATE_TRAVEL_EXPENSE: {
        COST_OF_ELECTORAL_AGENT: 'costOfElectoralAgent',
        COST_OF_PERSONNEL: 'costOfPersonnel',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      DOMESTIC_MEETING_EXPENSE: {
        RENTAL_OF_VENUE: 'rentalOfVenue',
        LABOUR_COST: 'labourCost',
        RENT_OF_FURNITURE: 'rentOfFurniture',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      LEAFLET_EXPENSE: {
        NAME_OF_PRINTING_PRESS: 'nameOfPrintingPress',
        LEAFLET_COUNT: 'leafletCount',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      HANDBILL_EXPENSE: {
        NAME_OF_PRINTING_PRESS: 'nameOfPrintingPress',
        HANDBILL_COUNT: 'handbillCount',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      BANNER_EXPENSE: {
        NUMBER_OF_BANNERS: 'numberOfBanners',
        COST_OF_BANNER_CREATION: 'costOfBannerCreation',
        COST_OF_HANGING_BANNERS: 'costOfHangingBanners',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      DIGITAL_BANNER_EXPENSE: {
        DIGITAL_BANNER_EXPENSE: 'digitalBannerExpense',
        COST_OF_DIGITAL_BANNER_CREATION: 'costOfDigitalBannerCreation',
        COST_OF_HANGING_DIGITAL_BANNERS: 'costOfHangingDigitalBanners',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },

      ROAD_MEETING_EXPENSE: {
        NUMBER_OF_MEETINGS: 'numberOfMeetings',
        COST_OF_MIC: 'costOfMic',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },

      MIKING_EXPENSE: {
        RENTAL_OF_VEHICLES: 'rentalOfVehicles',
        MIKING_PERSON_COST: 'mikingPersonCost',
        MIKE_RENTAL_COST: 'mikeRentalCost',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      PORTRAIT_EXPENSE: {
        COST_OF_PORTRAITS: 'costOfPortrait',
        PORTRAIT_PRINTING_NAME: 'portraitPrintingName',
        COST_OF_PORTRAIT_MAKING: 'costOfPortraitMaking',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      SYMBOL_EXPENSE: {
        NUMBER_OF_SYMBOLS: 'numberOfSymbols',
        SYMBOL_CREATION_COST: 'symbolCreationsCost',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      OFFICE_INVITATION_EXPENSE: {
        NUMBER_OF_OFFICE: 'numberOfOffice',
        COST_OF_DAILY_ENTERTAINMENT: 'costOfDailyEntertainment',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      STAFF_EXPENSE: {
        NUMBER_OF_STAFF: 'numberOfStaff',
        PER_PERSON_COST: 'perPersonCost',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      ADVERTISEMENT_EXPENSE: {
        COST_OF_TELEVISION_ADVERTISEMENT: 'costOfTelevisionAdvertisement',
        COST_OF_OTHER_MEDIA: 'costOfOtherMedia',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
      OTHER_EXPENSE: {
        OTHER_EXPENSE: 'otherExpense',
        SECTOR_NAME: 'sectorName',
        AMOUNT_OF_COST: 'amountOfCost',
        TOTAL_POSSIBLE_COST: 'totalPossibleCost',
      },
    },
  },

  DYNAMIC_REPORT: {
    NAME_BN: 'nameBn',
    NAME_EN: 'nameEn',
    TAG: 'tag',
    QUERY_VALUE: 'queryValue',
    VALUE: 'value',
  },
};
