export const CREATE_SECOND_PART = {
  CREATE_SECOND_PART_REQUEST: 'CREATE_CANDIDATE_NOMINATION_FORM_SECOND_REQUEST',
  CREATE_SECOND_PART_SUCCESS: 'CREATE_CANDIDATE_NOMINATION_FORM_SECOND_SUCCESS',
  CREATE_SECOND_PART_FAILED: 'CREATE_CANDIDATE_NOMINATION_FORM_SECOND_FAILED',
  CREATE_SECOND_PART_INITIAL_STATE:
    'CREATE_CANDIDATE_NOMINATION_FORM_SECOND_INITIAL_STATE',
};

export const GET_SECOND_PART = {
  GET_SECOND_PART_REQUEST: 'GET_CANDIDATE_NOMINATION_FORM_SECOND_PART_REQUEST',
  GET_SECOND_PART_SUCCESS: 'GET_CANDIDATE_NOMINATION_FORM_SECOND_PART_SUCCESS',
  GET_SECOND_PART_FAILED: 'GET_CANDIDATE_NOMINATION_FORM_SECOND_PART_FAILED',
  GET_SECOND_PART_INITIAL_STATE:
    'GET_CANDIDATE_NOMINATION_FORM_SECOND_PART_INITIAL_STATE',
};
