apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.variables.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.variables.imageRepository }}:{{ .Values.variables.imageAppVersion }}"
          imagePullPolicy: {{ .Values.variables.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.variables.serviceTargetPort }}
              name: http
          resources:
{{- toYaml .Values.resources | default "{}" | indent 12 }}
      imagePullSecrets:
        - name: {{ .Values.variables.imagePullSecrets }}

