import { FORM_FIELDS } from '@constants/forms';
import * as yup from 'yup';

export const POLLING_PERSONNEL_LETTER_SEARCH =
  FORM_FIELDS.POLLING_PERSONNEL_LETTER_SEARCH;

export const centerOfficerUpazilaListValidation = yup.object().shape({
  [POLLING_PERSONNEL_LETTER_SEARCH.NAME]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.NAME_ERROR_MESSAGE'),
  [POLLING_PERSONNEL_LETTER_SEARCH.DESIGNATION]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.DESIGNATION_ERROR_MESSAGE'),
});
export const centerOfficerDefaultListValidation = yup.object().shape({
  [POLLING_PERSONNEL_LETTER_SEARCH.NAME]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.NAME_ERROR_MESSAGE'),
  [POLLING_PERSONNEL_LETTER_SEARCH.DESIGNATION]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.DESIGNATION_ERROR_MESSAGE'),
  [POLLING_PERSONNEL_LETTER_SEARCH.GOODS_DISTRIBUTION_DATE_AND_TIME]: yup
    .string()
    .required(
      'CENTER_BASED_OFFICER_LIST.GOODS_RECEIVING_DATE_AND_TIME_ERROR_MESSAGE',
    ),
  [POLLING_PERSONNEL_LETTER_SEARCH.GOODS_RECEIVED_DATE_AND_TIME]: yup
    .string()
    .required(
      'CENTER_BASED_OFFICER_LIST.GOODS_DISTRIBUTION_DATE_AND_TIME_ERROR_MESSAGE',
    ),
  [POLLING_PERSONNEL_LETTER_SEARCH.TRAINING_DATE_AND_TIME]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.TRAINING_DATE_AND_TIME_ERROR_MESSAGE'),
  [POLLING_PERSONNEL_LETTER_SEARCH.TRAINING_PLACE]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.TRAINING_PLACE_ERROR_MESSAGE'),
  [POLLING_PERSONNEL_LETTER_SEARCH.TRAINING_ROOM]: yup
    .string()
    .required('CENTER_BASED_OFFICER_LIST.TRAINING_ROOM_ERROR_MESSAGE'),
});
