export const CREATE_CANDIDATE_PERSONAL_INFO = {
  CREATE_CANDIDATE_PERSONAL_INFO_REQUEST:
    'CREATE_CANDIDATE_PERSONAL_INFO_REQUEST',
  CREATE_CANDIDATE_PERSONAL_INFO_SUCCESS:
    'CREATE_CANDIDATE_PERSONAL_INFO_SUCCESS',
  CREATE_CANDIDATE_PERSONAL_INFO_FAILED:
    'CREATE_CANDIDATE_PERSONAL_INFO_FAILED',
  CREATE_CANDIDATE_PERSONAL_INITIAL_STATE:
    'CREATE_CANDIDATE_PERSONAL_INITIAL_STATE',
};

export const GET_CANDIDATE_PERSONAL_INFO = {
  GET_CANDIDATE_PERSONAL_INFO_REQUEST: 'GET_CANDIDATE_PERSONAL_INFO_REQUEST',
  GET_CANDIDATE_PERSONAL_INFO_SUCCESS: 'GET_CANDIDATE_PERSONAL_INFO_SUCCESS',
  GET_CANDIDATE_PERSONAL_INFO_FAILED: 'GET_CANDIDATE_PERSONAL_INFO_FAILED',
};

export const GET_CANDIDATE_CHILDREN = {
  GET_CANDIDATE_CHILDREN_REQUEST: 'GET_CANDIDATE_CHILDREN_REQUEST',
  GET_CANDIDATE_CHILDREN_SUCCESS: 'GET_CANDIDATE_CHILDREN_SUCCESS',
  GET_CANDIDATE_CHILDREN_FAILED: 'GET_CANDIDATE_CHILDREN_FAILED',
};

export const GET_CANDIDATE_CHILD = {
  GET_CANDIDATE_CHILD_REQUEST: 'GET_CANDIDATE_CHILD_REQUEST',
  GET_CANDIDATE_CHILD_SUCCESS: 'GET_CANDIDATE_CHILD_SUCCESS',
  GET_CANDIDATE_CHILD_FAILED: 'GET_CANDIDATE_CHILD_FAILED',
};

export const UPDATE_CANDIDATE_CHILD = {
  UPDATE_CANDIDATE_CHILD_REQUEST: 'UPDATE_CANDIDATE_CHILD_REQUEST',
  UPDATE_CANDIDATE_CHILD_SUCCESS: 'UPDATE_CANDIDATE_CHILD_SUCCESS',
  UPDATE_CANDIDATE_CHILD_FAILED: 'UPDATE_CANDIDATE_CHILD_FAILED',
};

export const DELETE_CANDIDATE_CHILD = {
  DELETE_CANDIDATE_CHILD_REQUEST: 'DELETE_CANDIDATE_CHILD_REQUEST',
  DELETE_CANDIDATE_CHILD_SUCCESS: 'DELETE_CANDIDATE_CHILD_SUCCESS',
  DELETE_CANDIDATE_CHILD_FAILED: 'DELETE_CANDIDATE_CHILD_FAILED',
};
