export const ELECTION = {
  SCHEDULE_DECLARATION: {
    ELECTION_NAME_ENGLISH: 'nameEn',
    ELECTION_NAME_BANGLA: 'nameBn',
    ELECTION_TYPE: 'electionTypeId',
    DATE_OF_DECLARATION: 'dateOfDeclaration',
    NOMINATION_SUBMISSION_LAST_DATE: 'dateOfNominationSubmission',
    NOMINATION_SELECTION_DATE_RANGE_START: 'dateOfNominationSelectionStart',
    NOMINATION_SELECTION_DATE_RANGE_END: 'dateOfNominationSelectionEnd',
    APPEAL_DATE: 'dateOfAppealSubmission',
    APPEAL_JUDGEMENT_DATE: 'dateOfAppealJudgement',
    NOMINATION_WITHDRAWAL_LAST_DATE: 'dateOfNominationWithdrawal',
    SYMBOL_ALLOCATION_DATE: 'dateOfAssignedSymbol',
    DATE_OF_ELECTION: 'dateOfElection',
    DATE_OF_GAZETTE: 'dateOfGazette',
    // NOTIFICATION_ISSUE_DATE: 'notificationIssueDate',
    VOTE_CASTING_START_TIME: 'voteCastingStartTime',
    VOTE_CASTING_END_TIME: 'voteCastingEndTime',
    UPLOAD_SCHEDULE_COPY: 'fileOfSchedule',
    UPLOAD_OTHER_FILES: 'fileOfOthers',
    REMARKS_ON_SCHEDULE: 'scheduleComment',
    ONLINE_NOMINATION: 'isOnlineNomination',
    IN_ACTIVE: 'isActive',
    MINIMUM_AGE: 'minimumAge',
    DATE_UPTO_WHICH_AGE_WILL_BE_CALCULATED: 'dateOfAgeComparedFrom',
    TOTAL_REGIONS: 'totalRegion',
    TOTAL_DISTRICTS: 'totalDistrict',
    POLLING_CENTER: 'totalPollingCenter',
    POLLING_BOOTH: 'totalPollingBooth',
    SEAT_NUMBERS: 'totalSeat',
    RETURNING_OFFICER: 'totalReturningOfficer',
    ASSISTANT_RETURNING_OFFICER: 'totalAssistantReturningOfficer',
    PRESIDING_OFFICER: 'totalPresidingOfficer',
    ASSISTANT_PRESIDING_OFFICER: 'totalAssistantPresidingOfficer',
    POLLING_OFFICER: 'totalPollingOfficer',
    BY_ELECTION: 'isByElection',
    ELECTION_NAME: 'parentElectionScheduleIds',
    SEAT_VACANCY_DATE: 'seatVacancyDate',
    REASON_OF_BY_ELECTION: 'byElectionReasons',
    REMARK_ON_BY_ELECTION: 'byElectionComments',
  },

  ELECTION_SETTINGS: {
    ELECTION_TYPE: 'electionTypeId',
    ELECTION_NAME: 'electionScheduleId',
    CANDIDATE_TYPE: 'candidateTypeId',
    DISTRICT: 'district',
    ELECTION_AREA: 'electionArea',
    ELECTION_FILE: 'electionFile',
    SUB_DISTRICT: 'subDistrict',
    ELECTION_SEAT_NO: 'electionSeatNo',
    SEAT_NAME: 'seatName',
    MUNICIPALITY: 'municipality',
    UNION: 'union',
    TAB_CENTER: 'tabCenter',
    EVM: 'evm',
    UNION_WARD: 'unionWard',
    NOMINATION_LAST_DATE: 'lastDateOfSubmit',
    SCHEDULE_FILE: 'scheduleFile',
    AREA_VOTE_CENTER: 'isVoterAreaDivided',
    ELECTION_BY_TAB: 'isResultFromTab',
    ELECTION_BY_EVM: 'electionByEvm',
    IS_ACTIVE: 'isActive',
    NOMINATION_SUBMISSION_LAST_DATE: 'dateOfNominationSubmission',
    SCHEDULE_FILE_UPLOAD: 'scheduleFile',
  },

  NOMINATION_LETTER: {
    ELECTION_TYPE: 'electionTypeName',
    CANDIDATE_TYPE: 'candidateTypeName',
    LETTER: 'letter',
    NOMINATION_FILE: 'file',
  },

  POSSIBLE_ELECTION: {
    DIVISION: 'possibleElectionDivision',
    DISTRICT: 'possibleElectionDistrict',
    UPAZILA: 'possibleElectionUpazila',
    ROM: 'possibleElectionRom',
    UNION_OR_WARD: 'possibleElectionUnion',
    ELECTION_TYPE: 'possibleElectionType',
    DATE: 'possibleElectionDate',
    FROM: 'possibleElectionFrom',
  },

  ELECTION_TRANSFER: {
    CONFIRMATION_MODAL: {
      ELECTION_NAME: 'electionScheduleId',
      ELECTION_CANDIDATE: 'isCandidate',
      ELECTION_CENTER: 'isPollingCenter',
      ELECTION_CENTER_OFFICER: 'isPollingPersonnel',
    },
  },
};
