export const ADD_NEW_NOMINATION = {
  ADD_NEW_NOMINATION_REQUEST: 'ADD_NEW_NOMINATION_REQUEST',
  ADD_NEW_NOMINATION_SUCCESS: 'ADD_NEW_NOMINATION_SUCCESS',
  ADD_NEW_NOMINATION_FAILED: 'ADD_NEW_NOMINATION_FAILED',
  ADD_NEW_NOMINATION_RESTORE: 'ADD_NEW_NOMINATION_RESTORE',
};
