export const CREATE_MOVABLE_PROPERTY = {
  CREATE_MOVABLE_PROPERTY_REQUEST: 'CREATE_AFFIDAVIT_MOVABLE_PROPERTY_REQUEST',
  CREATE_MOVABLE_PROPERTY_SUCCESS: 'CREATE_AFFIDAVIT_MOVABLE_PROPERTY_SUCCESS',
  CREATE_MOVABLE_PROPERTY_FAILED: 'CREATE_AFFIDAVIT_MOVABLE_PROPERTY_FAILED',
  CREATE_MOVABLE_PROPERTY_INITIAL_STATE:
    'CREATE_AFFIDAVIT_MOVABLE_PROPERTY_INITIAL_STATE',
};

export const GET_MOVABLE_PROPERTY = {
  GET_MOVABLE_PROPERTY_REQUEST: 'GET_AFFIDAVIT_MOVABLE_PROPERTY_REQUEST',
  GET_MOVABLE_PROPERTY_SUCCESS: 'GET_AFFIDAVIT_MOVABLE_PROPERTY_SUCCESS',
  GET_MOVABLE_PROPERTY_FAILED: 'GET_AFFIDAVIT_MOVABLE_PROPERTY_FAILED',
};

export const CREATE_IMMOVABLE_PROPERTY = {
  CREATE_IMMOVABLE_PROPERTY_REQUEST:
    'CREATE_AFFIDAVIT_IMMOVABLE_PROPERTY_REQUEST',
  CREATE_IMMOVABLE_PROPERTY_SUCCESS:
    'CREATE_AFFIDAVIT_IMMOVABLE_PROPERTY_SUCCESS',
  CREATE_IMMOVABLE_PROPERTY_FAILED:
    'CREATE_AFFIDAVIT_IMMOVABLE_PROPERTY_FAILED',
  CREATE_IMMOVABLE_PROPERTY_INITIAL_STATE:
    'CREATE_AFFIDAVIT_IMMOVABLE_PROPERTY_INITIAL_STATE',
};

export const GET_IMMOVABLE_PROPERTY = {
  GET_IMMOVABLE_PROPERTY_REQUEST: 'GET_AFFIDAVIT_IMMOVABLE_PROPERTY_REQUEST',
  GET_IMMOVABLE_PROPERTY_SUCCESS: 'GET_AFFIDAVIT_IMMOVABLE_PROPERTY_SUCCESS',
  GET_IMMOVABLE_PROPERTY_FAILED: 'GET_AFFIDAVIT_IMMOVABLE_PROPERTY_FAILED',
};

export const CREATE_LIABILITIES = {
  CREATE_LIABILITIES_REQUEST: 'CREATE_AFFIDAVIT_LIABILITIES_REQUEST',
  CREATE_LIABILITIES_SUCCESS: 'CREATE_AFFIDAVIT_LIABILITIES_SUCCESS',
  CREATE_LIABILITIES_FAILED: 'CREATE_AFFIDAVIT_LIABILITIES_FAILED',
  CREATE_LIABILITIES_INITIAL_STATE:
    'CREATE_AFFIDAVIT_LIABILITIES_INITIAL_STATE',
};

export const GET_LIABILITIES = {
  GET_LIABILITIES_REQUEST: 'GET_AFFIDAVIT_LIABILITIES_REQUEST',
  GET_LIABILITIES_SUCCESS: 'GET_AFFIDAVIT_LIABILITIES_SUCCESS',
  GET_LIABILITIES_FAILED: 'GET_AFFIDAVIT_LIABILITIES_FAILED',
};

export const UPDATE_LIABILITIES = {
  UPDATE_LIABILITIES_REQUEST: 'UPDATE_AFFIDAVIT_LIABILITIES_REQUEST',
  UPDATE_LIABILITIES_SUCCESS: 'UPDATE_AFFIDAVIT_LIABILITIES_SUCCESS',
  UPDATE_LIABILITIES_FAILED: 'UPDATE_AFFIDAVIT_MOVABLE_PROPERTY_FAILED',
};

export const GET_LIABILITY_CHILDREN = {
  GET_LIABILITY_CHILDREN_REQUEST: 'GET_AFFIDAVIT_LIABILITY_CHILDREN_REQUEST',
  GET_LIABILITY_CHILDREN_SUCCESS: 'GET_AFFIDAVIT_LIABILITY_CHILDREN_SUCCESS',
  GET_LIABILITY_CHILDREN_FAILED: 'GET_AFFIDAVIT_LIABILITY_CHILDREN_FAILED',
};

export const GET_LIABILITY_CHILD = {
  GET_LIABILITY_CHILD_REQUEST: 'GET_AFFIDAVIT_LIABILITY_CHILD_REQUEST',
  GET_LIABILITY_CHILD_SUCCESS: 'GET_AFFIDAVIT_LIABILITY_CHILD_SUCCESS',
  GET_LIABILITY_CHILD_FAILED: 'GET_AFFIDAVIT_LIABILITY_CHILD_FAILED',
};

export const UPDATE_LIABILITY_CHILD = {
  UPDATE_LIABILITY_CHILD_REQUEST: 'UPDATE_AFFIDAVIT_LIABILITY_CHILD_REQUEST',
  UPDATE_LIABILITY_CHILD_SUCCESS: 'UPDATE_AFFIDAVIT_LIABILITY_CHILD_SUCCESS',
  UPDATE_LIABILITY_CHILD_FAILED: 'UPDATE_AFFIDAVIT_LIABILITY_CHILD_FAILED',
};

export const DELETE_LIABILITY_CHILD = {
  DELETE_LIABILITY_CHILD_REQUEST: 'DELETE_AFFIDAVIT_LIABILITY_CHILD_REQUEST',
  DELETE_LIABILITY_CHILD_SUCCESS: 'DELETE_AFFIDAVIT_LIABILITY_CHILD_SUCCESS',
  DELETE_LIABILITY_CHILD_FAILED: 'DELETE_AFFIDAVIT_LIABILITY_CHILD_FAILED',
};

export const GET_COMMITMENT_ACHIEVEMENT_CHILDREN = {
  GET_COMMITMENT_ACHIEVEMENT_CHILDREN_REQUEST:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILDREN_REQUEST',
  GET_COMMITMENT_ACHIEVEMENT_CHILDREN_SUCCESS:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILDREN_SUCCESS',
  GET_COMMITMENT_ACHIEVEMENT_CHILDREN_FAILED:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILDREN_FAILED',
};

export const GET_COMMITMENT_ACHIEVEMENT_CHILD = {
  GET_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST',
  GET_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS',
  GET_COMMITMENT_ACHIEVEMENT_CHILD_FAILED:
    'GET_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_FAILED',
};

export const UPDATE_COMMITMENT_ACHIEVEMENT_CHILD = {
  UPDATE_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST:
    'UPDATE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST',
  UPDATE_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS:
    'UPDATE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS',
  UPDATE_COMMITMENT_ACHIEVEMENT_CHILD_FAILED:
    'UPDATE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_FAILED',
};

export const DELETE_COMMITMENT_ACHIEVEMENT_CHILD = {
  DELETE_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST:
    'DELETE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_REQUEST',
  DELETE_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS:
    'DELETE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_SUCCESS',
  DELETE_COMMITMENT_ACHIEVEMENT_CHILD_FAILED:
    'DELETE_AFFIDAVIT_COMMITMENT_ACHIEVEMENT_CHILD_FAILED',
};
