export const CREATE_INCOME_SOURCE_DETAILS_SECOND_PART = {
  CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_REQUEST:
    'CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_REQUEST',
  CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_SUCCESS:
    'CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_SUCCESS',
  CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_FAILED:
    'CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_FAILED',
  CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_INITIAL_STATE:
    'CREATE_INCOME_SOURCE_DETAILS_SECOND_PART_INITIAL_STATE',
};

export const GET_INCOME_SOURCE_SECOND_PART_DETAILS = {
  GET_INCOME_SOURCE_SECOND_PART_REQUEST:
    'GET_INCOME_SOURCE_SECOND_PART_REQUEST',
  GET_INCOME_SOURCE_SECOND_PART_SUCCESS:
    'GET_INCOME_SOURCE_SECOND_PART_SUCCESS',
  GET_INCOME_SOURCE_SECOND_PART_FAILED: 'GET_INCOME_SOURCE_SECOND_PART_FAILED',
  GET_INCOME_SOURCE_SECOND_PART_INITIAL_STATE:
    'GET_INCOME_SOURCE_SECOND_PART_INITIAL_STATE',
};
