export const CREATE_INCOME_SOURCE_DETAILS = {
  CREATE_INCOME_SOURCE_DETAILS_REQUEST: 'CREATE_INCOME_SOURCE_DETAILS_REQUEST',
  CREATE_INCOME_SOURCE_DETAILS_SUCCESS: 'CREATE_INCOME_SOURCE_DETAILS_SUCCESS',
  CREATE_INCOME_SOURCE_DETAILS_FAILED: 'CREATE_INCOME_SOURCE_DETAILS_FAILED',
  CREATE_INCOME_SOURCE_DETAILS_INITIAL_STATE:
    'CREATE_INCOME_SOURCE_DETAILS_INITIAL_STATE',
};

export const GET_INCOME_SOURCE_DETAILS = {
  GET_INCOME_SOURCE_DETAILS_REQUEST: 'GET_INCOME_SOURCE_DETAILS_REQUEST',
  GET_INCOME_SOURCE_DETAILS_SUCCESS: 'GET_INCOME_SOURCE_DETAILS_SUCCESS',
  GET_INCOME_SOURCE_DETAILS_FAILED: 'GET_INCOME_SOURCE_DETAILS_FAILED',
};

export const UPDATE_SELF_FUNDING = {
  UPDATE_SELF_FUNDING_REQUEST: 'UPDATE_SELF_FUNDING_REQUEST',
  UPDATE_SELF_FUNDING_SUCCESS: 'UPDATE_SELF_FUNDING_SUCCESS',
  UPDATE_SELF_FUNDING_FAILED: 'UPDATE_SELF_FUNDING_FAILED',
};

export const UPDATE_RELATIVE_FUNDING = {
  UPDATE_RELATIVE_FUNDING_REQUEST: 'UPDATE_RELATIVE_FUNDING_REQUEST',
  UPDATE_RELATIVE_FUNDING_SUCCESS: 'UPDATE_RELATIVE_FUNDING_SUCCESS',
  UPDATE_RELATIVE_FUNDING_FAILED: 'UPDATE_RELATIVE_FUNDING_FAILED',
};

export const UPDATE_OTHER_FUNDING = {
  UPDATE_OTHER_FUNDING_REQUEST: 'UPDATE_OTHER_FUNDING_REQUEST',
  UPDATE_OTHER_FUNDING_SUCCESS: 'UPDATE_OTHER_FUNDING_SUCCESS',
  UPDATE_OTHER_FUNDING_FAILED: 'UPDATE_OTHER_FUNDING_FAILED',
};

export const DELETE_SELF_FUNDING = {
  DELETE_SELF_FUNDING_REQUEST: 'DELETE_SELF_FUNDING_REQUEST',
  DELETE_SELF_FUNDING_SUCCESS: 'DELETE_SELF_FUNDING_SUCCESS',
  DELETE_SELF_FUNDING_FAILED: 'DELETE_SELF_FUNDING_FAILED',
};

export const DELETE_RELATIVE_FUNDING = {
  DELETE_RELATIVE_FUNDING_REQUEST: 'DELETE_RELATIVE_FUNDING_REQUEST',
  DELETE_RELATIVE_FUNDING_SUCCESS: 'DELETE_RELATIVE_FUNDING_SUCCESS',
  DELETE_RELATIVE_FUNDING_FAILED: 'DELETE_RELATIVE_FUNDING_FAILED',
};

export const DELETE_OTHER_FUNDING = {
  DELETE_OTHER_FUNDING_REQUEST: 'DELETE_OTHER_FUNDING_REQUEST',
  DELETE_OTHER_FUNDING_SUCCESS: 'DELETE_OTHER_FUNDING_SUCCESS',
  DELETE_OTHER_FUNDING_FAILED: 'DELETE_OTHER_FUNDING_FAILED',
};
